services:
  gateway_server:
    build: ./compose
    ports:
      - "5000:5000"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
  registry_server:
    build: ./compose
    ports:
      - "5000:5000"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
  training_server:
    build: ./compose
    ports:
      - "5000:5000"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  deployment_server:
    build: ./compose
    ports:
      - "5000:5000"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
