default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 2
val_check_interval: 0.25

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
# precision: 16